name: the_parker
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"
  # sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^1.2.0
  geolocator: ^6.2.0
  http: ^0.12.2
  custom_radio_grouped_button: ^1.0.0
  flutter_vector_icons: ^0.3.0
  extended_navbar_scaffold: 1.0.2+1
  mapbox_search: ^2.1.0
  mapbox_search_flutter: ^1.0.6+1
  flutter_map: ^0.8.2
  user_location: ^0.1.3
  flare_flutter: ^2.0.6
  eva_icons_flutter: ^2.0.0

  #State Management
  stacked: 1.7.7
  stacked_services: 0.6.6
  stacked_hooks: 0.1.3+2
  get_it: 5.0.6
  injectable: 1.0.7

  #Firebase

  #Authentication

  #Router

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_map: ^0.8.2

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: K2D
      fonts:
        - asset: assets/fonts/K2D-Light.ttf
          weight: 300
        - asset: assets/fonts/K2D-Regular.ttf
          weight: 400
        - asset: assets/fonts/K2D-Medium.ttf
          weight: 500
        - asset: assets/fonts/K2D-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/K2D-Bold.ttf
          weight: 700
        - asset: assets/fonts/K2D-ExtraBold.ttf
          weight: 900
